"""Create initial tables

Revision ID: 4ed4afba9445
Revises: 9a0b5c0f5c01
Create Date: 2025-09-26 14:29:39.748574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ed4afba9445'
down_revision: Union[str, None] = '9a0b5c0f5c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
