"""Create initial tables

Revision ID: 741060d0a7bd
Revises: 8cf0dbb3948d
Create Date: 2025-09-26 12:31:49.738907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '741060d0a7bd'
down_revision: Union[str, None] = '8cf0dbb3948d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
