"""Create initial tables

Revision ID: 7e4d5cc257e6
Revises: 7d0fcf9dce17
Create Date: 2025-09-26 14:11:07.802225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e4d5cc257e6'
down_revision: Union[str, None] = '7d0fcf9dce17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
