"""Create initial tables

Revision ID: 9a0b5c0f5c01
Revises: 7e4d5cc257e6
Create Date: 2025-09-26 14:19:11.704368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a0b5c0f5c01'
down_revision: Union[str, None] = '7e4d5cc257e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
